api_version = "2025-04"

[[extensions]]
name = "Coupon Discount"
handle = "coupon-discount"
uid = "ace70ae9-5701-d720-6d2b-6982cbda1c75dba60603"
type = "function"
description = "Applies coupon discounts (percentage or fixed amount) at checkout"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = "sh build.sh"
  path = "dist/function.wasm"
